#ifndef USER_H
#define USER_H

#include <string>
#include "database.h"

class User {
private:
    std::string username;
    std::string password;
    bool isAutoGenerated;

public:
    // Constructor
    User(const std::string& uname, const std::string& pwd, bool isAuto = false);

    // Getters
    std::string getUsername() const;
    std::string getPassword() const;
    bool IsAuto() const;

    // Utility
    static std::string hashPassword(const std::string& password);
    static std::string AutoGenerated();

    // Database interactions
    bool registerToDB(Database& db);
    bool loginFromDB(Database& db, const std::string& uname, const std::string& pwd);
    bool changePassword(Database& db, const std::string& newPassword);
};

#endif // USER_H