#ifndef USER_H
#define USER_H

#include <string>
#include "../sql/sqlite3.h"

class User {
private:
    std::string username;
    std::string password;
    bool isAutoGenerated;

public:
    User(const std::string& uname, const std::string& pwd, bool isAuto = false);

    std::string getUsername() const;
    std::string getPassword() const;
    bool IsAuto();
};

// Tạo mật khẩu ngẫu nhiên (cho admin)
std::string AutoGenerated();

// Hàm băm mật khẩu
std::string hashPassword(const std::string& password);

// Khởi tạo database và tạo bảng USERS nếu chưa có
bool createDatabase(sqlite3*& db);

// Kiểm tra xem username đã tồn tại chưa
bool findUser(sqlite3* db, const std::string& username);

// Đăng ký tài khoản (user hoặc admin)
bool registerUser(sqlite3* db, const std::string& username, const std::string& password, bool isAuto);

// Đăng nhập tài khoản (và bắt đổi mật khẩu nếu là mật khẩu tự sinh)
bool loginUser(sqlite3* db, const std::string& username, const std::string& password);

// Đổi mật khẩu cho tài khoản
bool ChangePassword(sqlite3* db, const std::string& username, const std::string& newPassword);

#endif