#include "../include/ui.h"
#include "../include/user.h"
#include <cstdlib>
#include "../sql/sqlite3.h"
using namespace std;

int main() {
    sqlite3* db;
    if (!createDatabase(db)) {
        showMessage("Failed to create or open database.");
        return 1;
    }

    while (true) {
        showMenu();
        char choice = getMenuChoice();
        system("cls");

        if (choice == '1') {  // LOGIN
            while (true) {
                showLoginScreen();
                string username = getInput("Please enter your username: ");
                string password = getInput("Please enter your password: ");
                
                if (loginUser(db, username, password)) {
                    showMessage(">> SUCCESSFULLY LOGIN <<");
                    /*
                        DEVELOPING....
                        MOVE TO THE MAIN TRANSACTION MENU IN HERE;
                    */
                    system("pause");
                    system("cls");
                    break;
                } else {
                    showMessage(">> LOGIN FAILED. Please try again.\n");
                    system("pause");
                    system("cls");
                }
            }

        } else if (choice == '2') {  // REGISTER
            while (true) {
                showRegisterScreen();
                string username = getInput("Please enter your username: ");
                string password = getInput("Please enter your password: ");
                bool isAuto = false;

                if (registerUser(db, username, password, isAuto)) {
                    showMessage(">>> SUCCESSFULLY CREATED ACCOUNT <<<");
                    system("pause");
                    system("cls");
                    break;
                } else {
                    showMessage("Invalid input or username exists!\n");
                    system("pause");
                    system("cls");
                }
            }

        } else if (choice == '3') {  // REGISTER FOR MANAGER
            showRegisterScreenForMnger();
            while (true) {
                string adminPassword = getInput("Enter admin password: ");
                if (adminPassword == "admin123") {
                    system("cls");
                    break;
                } else {
                    showMessage("WRONG PASSWORD\n");
                    system("pause");
                    system("cls");
                }
            }

            string username = getInput("Please enter your username: ");
            string autoPassword = AutoGenerated();
            bool isAuto = true;

            if (registerUser(db, username, autoPassword, isAuto)) {
                showMessage("User created! Auto-generated password: " + autoPassword);
                system("pause");
                system("cls");
            } else {
                showMessage("Invalid input or username exists!\n");
                system("pause");
                system("cls");
            }
        }
    }

    sqlite3_close(db);
    return 0;
}