#include "../include/ui.h"
#include "../include/user.h"
#include "../include/database.h"
#include <cstdlib>
using namespace std;

int main() {
    Database db;

    // Kết nối và tạo database
    if (!db.connect("data/users.db")) {
        showMessage("Failed to create or open database.");
        return 1;
    }

    while (true) {
        showMenu();
        char choice = getMenuChoice();
        system("cls");

        if (choice == '1') {  // LOGIN
            while (true) {
                showLoginScreen();
                string username = getInput("Please enter your username: ");
                string password = getInput("Please enter your password: ");

                User tempUser("", "", false);
                if (tempUser.loginFromDB(db, username, password)) {
                    showMessage(">> SUCCESSFULLY LOGIN <<");
                    /*
                        DEVELOPING...
                        MOVE TO THE MAIN TRANSACTION MENU IN HERE;
                    */
                    system("pause");
                    system("cls");
                    break;
                } else {
                    showMessage(">> LOGIN FAILED. Please try again.\n");
                    system("pause");
                    system("cls");
                }
            }

        } else if (choice == '2') {  // REGISTER
            while (true) {
                showRegisterScreen();
                string username = getInput("Please enter your username: ");
                string password = getInput("Please enter your password: ");

                User newUser(username, password, false);
                if (newUser.registerToDB(db)) {
                    showMessage(">>> SUCCESSFULLY CREATED ACCOUNT <<<");
                    system("pause");
                    system("cls");
                    break;
                } else {
                    showMessage("Invalid input or username exists!\n");
                    system("pause");
                    system("cls");
                }
            }

        } else if (choice == '3') {  // REGISTER FOR MANAGER
            showRegisterScreenForMnger();

            while (true) {
                string adminPassword = getInput("Enter admin password: ");
                if (adminPassword == "admin123") {
                    system("cls");
                    break;
                } else {
                    showMessage("WRONG PASSWORD\n");
                    system("pause");
                    system("cls");
                }
            }

            string username = getInput("Please enter your username: ");
            string autoPassword = User::AutoGenerated();

            User newUser(username, autoPassword, true);
            if (newUser.registerToDB(db)) {
                showMessage("User created! Auto-generated password: " + autoPassword);
                system("pause");
                system("cls");
            } else {
                showMessage("Invalid input or username exists!\n");
                system("pause");
                system("cls");
            }
        }
    }

    return 0;
}